[package]
name = "cairo_clob"
version = "0.1.0"

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true
allowed-libfuncs-list.name = "all"
# allowed-libfuncs-deny = false

[dependencies]
starknet = "2.2.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.6.0" }
